version: "3.4"

services: 
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    volume_driver: 
      - ./v2ray/config.json:/etc/v2ray/config.json
    expose: 
      - "10000"
  caddy:
    image: caddy:latest
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/cert:/root/.caddy
      - ./website:/srv
